- hosts: localhost
  tasks:
        - name: Installing epel-release
          package:
                name: "epel-release"
                state: present
        - name: Installing pip 
          package:
                name: "python-pip"
                state: present
        - name: Installing docker service
          package:
                name: "docker-ce"
                state: present
        - name: Making docker service permanent 
          service:
                name: "docker"
                state: started
                enabled: yes
        - name: Installing docker (python module required by docker_image and docker_container)
          pip:
                name: "docker"
                state: present
        - name: Loading docker image from tar file 
          docker_image:
                name: "ubuntu:latest"
                state: present
                load_path: "/home/om/Downloads/Transfer/rhel7_5_software_extras/ubuntu-latest.tar"
        - name: Creating a container from the image we loaded
          docker_container:
                name: "UbuntuTry4"
                image: "ubuntu:latest"
                tty: yes
                interactive: yes
